name: Threads
on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]
jobs:
  Quality:
    runs-on: ubuntu-latest
    steps:
      - uses: adambco/pr-quality-enforcer-action@master
        with:
          CHECK_FOR_MILESTONE: true
          CHECK_FOR_PROJECTS: true
          TYPE_LABELS: "bugfix,feature"
          PLATFORM_LABELS: "ios,android"
